package com.model;

/**
 * TDingdanxinxi generated by MyEclipse Persistence Tools
 */

public class TDingdanxinxi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String dingdanhao;	private String dingdanneirong;	private String dingdanjine;	private String goumairen;	private String dianhua;	private String dizhi;	private String beizhu;	private String iszf;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TDingdanxinxi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getDingdanhao()
	{
		return dingdanhao;
	}
	public void setDingdanhao(String dingdanhao)
	{
		this.dingdanhao = dingdanhao;
	}		public String getDingdanneirong()
	{
		return dingdanneirong;
	}
	public void setDingdanneirong(String dingdanneirong)
	{
		this.dingdanneirong = dingdanneirong;
	}		public String getDingdanjine()
	{
		return dingdanjine;
	}
	public void setDingdanjine(String dingdanjine)
	{
		this.dingdanjine = dingdanjine;
	}		public String getGoumairen()
	{
		return goumairen;
	}
	public void setGoumairen(String goumairen)
	{
		this.goumairen = goumairen;
	}		public String getDianhua()
	{
		return dianhua;
	}
	public void setDianhua(String dianhua)
	{
		this.dianhua = dianhua;
	}		public String getDizhi()
	{
		return dizhi;
	}
	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
		public String getIszf()
	{
		return iszf;
	}
	public void setIszf(String iszf)
	{
		this.iszf = iszf;
	}
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
