package com.model;

/**
 * TGoumai generated by MyEclipse Persistence Tools
 */

public class TGoumai implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shangpinbianhao;	private String shangpinmingcheng;	private String shangpinleibie;	private String zhiyaogongsi;	private String jiage;	private String kucun;	private String xiaoliang;	private String goumaishuliang;	private String goumaijine;	private String goumairen;	private String issh;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TGoumai()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShangpinbianhao()
	{
		return shangpinbianhao;
	}
	public void setShangpinbianhao(String shangpinbianhao)
	{
		this.shangpinbianhao = shangpinbianhao;
	}		public String getShangpinmingcheng()
	{
		return shangpinmingcheng;
	}
	public void setShangpinmingcheng(String shangpinmingcheng)
	{
		this.shangpinmingcheng = shangpinmingcheng;
	}		public String getShangpinleibie()
	{
		return shangpinleibie;
	}
	public void setShangpinleibie(String shangpinleibie)
	{
		this.shangpinleibie = shangpinleibie;
	}		public String getZhiyaogongsi()
	{
		return zhiyaogongsi;
	}
	public void setZhiyaogongsi(String zhiyaogongsi)
	{
		this.zhiyaogongsi = zhiyaogongsi;
	}		public String getJiage()
	{
		return jiage;
	}
	public void setJiage(String jiage)
	{
		this.jiage = jiage;
	}		public String getKucun()
	{
		return kucun;
	}
	public void setKucun(String kucun)
	{
		this.kucun = kucun;
	}		public String getXiaoliang()
	{
		return xiaoliang;
	}
	public void setXiaoliang(String xiaoliang)
	{
		this.xiaoliang = xiaoliang;
	}		public String getGoumaishuliang()
	{
		return goumaishuliang;
	}
	public void setGoumaishuliang(String goumaishuliang)
	{
		this.goumaishuliang = goumaishuliang;
	}		public String getGoumaijine()
	{
		return goumaijine;
	}
	public void setGoumaijine(String goumaijine)
	{
		this.goumaijine = goumaijine;
	}		public String getGoumairen()
	{
		return goumairen;
	}
	public void setGoumairen(String goumairen)
	{
		this.goumairen = goumairen;
	}	
	
		public String getIssh()
	{
		return issh;
	}
	public void setIssh(String issh)
	{
		this.issh = issh;
	}
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
