package com.model;

/**
 * TShangpinxinxi generated by MyEclipse Persistence Tools
 */

public class TShangpinxinxi implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shangpinbianhao;	private String shangpinmingcheng;	private String shangpinleibie;	private String zhiyaogongsi;	private String jiage;	private String kucun;	private String xiaoliang;	private String tupian;	private String yaopinjianjie;	private String yaoxiao;	private String dianzan_d;	private String dianzan_c;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TShangpinxinxi()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShangpinbianhao()
	{
		return shangpinbianhao;
	}
	public void setShangpinbianhao(String shangpinbianhao)
	{
		this.shangpinbianhao = shangpinbianhao;
	}		public String getShangpinmingcheng()
	{
		return shangpinmingcheng;
	}
	public void setShangpinmingcheng(String shangpinmingcheng)
	{
		this.shangpinmingcheng = shangpinmingcheng;
	}		public String getShangpinleibie()
	{
		return shangpinleibie;
	}
	public void setShangpinleibie(String shangpinleibie)
	{
		this.shangpinleibie = shangpinleibie;
	}		public String getZhiyaogongsi()
	{
		return zhiyaogongsi;
	}
	public void setZhiyaogongsi(String zhiyaogongsi)
	{
		this.zhiyaogongsi = zhiyaogongsi;
	}		public String getJiage()
	{
		return jiage;
	}
	public void setJiage(String jiage)
	{
		this.jiage = jiage;
	}		public String getKucun()
	{
		return kucun;
	}
	public void setKucun(String kucun)
	{
		this.kucun = kucun;
	}		public String getXiaoliang()
	{
		return xiaoliang;
	}
	public void setXiaoliang(String xiaoliang)
	{
		this.xiaoliang = xiaoliang;
	}		public String getTupian()
	{
		return tupian;
	}
	public void setTupian(String tupian)
	{
		this.tupian = tupian;
	}		public String getYaopinjianjie()
	{
		return yaopinjianjie;
	}
	public void setYaopinjianjie(String yaopinjianjie)
	{
		this.yaopinjianjie = yaopinjianjie;
	}		public String getYaoxiao()
	{
		return yaoxiao;
	}
	public void setYaoxiao(String yaoxiao)
	{
		this.yaoxiao = yaoxiao;
	}		public String getDianzan_d()
	{
		return dianzan_d;
	}
	public void setDianzan_d(String dianzan_d)
	{
		this.dianzan_d = dianzan_d;
	}		public String getDianzan_c()
	{
		return dianzan_c;
	}
	public void setDianzan_c(String dianzan_c)
	{
		this.dianzan_c = dianzan_c;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
