package com.model;

/**
 * TShoucangjilu generated by MyEclipse Persistence Tools
 */

public class TShoucangjilu implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String username;	private String xwid;	private String ziduan;	private String biao;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TShoucangjilu()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getUsername()
	{
		return username;
	}
	public void setUsername(String username)
	{
		this.username = username;
	}		public String getXwid()
	{
		return xwid;
	}
	public void setXwid(String xwid)
	{
		this.xwid = xwid;
	}		public String getZiduan()
	{
		return ziduan;
	}
	public void setZiduan(String ziduan)
	{
		this.ziduan = ziduan;
	}		public String getBiao()
	{
		return biao;
	}
	public void setBiao(String biao)
	{
		this.biao = biao;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
