package com.model;

/**
 * TYaopinleibie generated by MyEclipse Persistence Tools
 */

public class TYaopinleibie implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String leibie;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYaopinleibie()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getLeibie()
	{
		return leibie;
	}
	public void setLeibie(String leibie)
	{
		this.leibie = leibie;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
