package com.model;

/**
 * TYaopinruku generated by MyEclipse Persistence Tools
 */

public class TYaopinruku implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String shangpinbianhao;	private String shangpinmingcheng;	private String shangpinleibie;	private String zhiyaogongsi;	private String kucun;	private String rukushuliang;	private String rukuriqi;	private String rukushuoming;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYaopinruku()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getShangpinbianhao()
	{
		return shangpinbianhao;
	}
	public void setShangpinbianhao(String shangpinbianhao)
	{
		this.shangpinbianhao = shangpinbianhao;
	}		public String getShangpinmingcheng()
	{
		return shangpinmingcheng;
	}
	public void setShangpinmingcheng(String shangpinmingcheng)
	{
		this.shangpinmingcheng = shangpinmingcheng;
	}		public String getShangpinleibie()
	{
		return shangpinleibie;
	}
	public void setShangpinleibie(String shangpinleibie)
	{
		this.shangpinleibie = shangpinleibie;
	}		public String getZhiyaogongsi()
	{
		return zhiyaogongsi;
	}
	public void setZhiyaogongsi(String zhiyaogongsi)
	{
		this.zhiyaogongsi = zhiyaogongsi;
	}		public String getKucun()
	{
		return kucun;
	}
	public void setKucun(String kucun)
	{
		this.kucun = kucun;
	}		public String getRukushuliang()
	{
		return rukushuliang;
	}
	public void setRukushuliang(String rukushuliang)
	{
		this.rukushuliang = rukushuliang;
	}		public String getRukuriqi()
	{
		return rukuriqi;
	}
	public void setRukuriqi(String rukuriqi)
	{
		this.rukuriqi = rukuriqi;
	}		public String getRukushuoming()
	{
		return rukushuoming;
	}
	public void setRukushuoming(String rukushuoming)
	{
		this.rukushuoming = rukushuoming;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
