package com.model;

/**
 * TYonghu generated by MyEclipse Persistence Tools
 */

public class TYonghu implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String zhanghao;	private String mima;	private String xingming;	private String xingbie;	private String shouji;	private String shenfenzheng;	private String zhaopian;	private String beizhu;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYonghu()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getZhanghao()
	{
		return zhanghao;
	}
	public void setZhanghao(String zhanghao)
	{
		this.zhanghao = zhanghao;
	}		public String getMima()
	{
		return mima;
	}
	public void setMima(String mima)
	{
		this.mima = mima;
	}		public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}		public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}		public String getShouji()
	{
		return shouji;
	}
	public void setShouji(String shouji)
	{
		this.shouji = shouji;
	}		public String getShenfenzheng()
	{
		return shenfenzheng;
	}
	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}		public String getZhaopian()
	{
		return zhaopian;
	}
	public void setZhaopian(String zhaopian)
	{
		this.zhaopian = zhaopian;
	}		public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
