package com.model;

/**
 * TYouqinglianjie generated by MyEclipse Persistence Tools
 */

public class TYouqinglianjie implements java.io.Serializable
{

	// Fields

	private Integer id;
	private String wangzhanmingcheng;	private String wangzhi;	private String logo;	
	private String addtime;

	// Constructors

	/** default constructor */
	public TYouqinglianjie()
	{
	}


	// Property accessors

	public Integer getId()
	{
		return this.id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}


	

	
		public String getWangzhanmingcheng()
	{
		return wangzhanmingcheng;
	}
	public void setWangzhanmingcheng(String wangzhanmingcheng)
	{
		this.wangzhanmingcheng = wangzhanmingcheng;
	}		public String getWangzhi()
	{
		return wangzhi;
	}
	public void setWangzhi(String wangzhi)
	{
		this.wangzhi = wangzhi;
	}		public String getLogo()
	{
		return logo;
	}
	public void setLogo(String logo)
	{
		this.logo = logo;
	}	
	
	
	
	public String getAddtime()
	{
		return addtime;
	}
	public void setAddtime(String addtime)
	{
		this.addtime = addtime;
	}

}
